/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/w0sc7vhHof8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'
import { Crimson_Text } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"

export function Proveedor() {
  return (
    <div className="min-h-screen">
      <header className="flex items-center justify-between p-4 bg-orange-500 md:px-6 lg:px-8">
        <div className="flex items-center">
          <Link href="#" className="mr-4 font-bold" prefetch={false}>
            Inicio
          </Link>
          <img
            src="/placeholder.svg"
            alt="Omega Logo"
            width="70"
            height="60"
            style={{ aspectRatio: "70/60", objectFit: "cover" }}
          />
        </div>
        <div className="relative flex items-center w-full max-w-md">
          <Input type="search" placeholder="Buscar..." className="w-full pr-10" />
          <div className="absolute right-3 h-5 w-5 text-muted-foreground" />
        </div>
      </header>
      <div className="container mx-auto py-8 px-4 md:px-6">
        <div className="grid md:grid-cols-2 gap-8">
          <div className="bg-card rounded-lg shadow-sm p-6">
            <h2 className="text-2xl font-bold mb-4">Proveedor</h2>
            <div className="grid gap-4">
              <div>
                <h3 className="text-lg font-medium">Nombre</h3>
                <p>Jarol Moreno</p>
              </div>
              <div>
                <h3 className="text-lg font-medium">Contacto</h3>
                <p>John Doe</p>
                <p>3105751123</p>
              </div>
              <div>
                <h3 className="text-lg font-medium">Dirección</h3>
                <p>Bogota, Colombia</p>
                <p>Carrera 100 #139</p>
              </div>
            </div>
          </div>
          <div className="bg-card rounded-lg shadow-sm p-6">
            <h2 className="text-2xl font-bold mb-4">Productos por distribuir</h2>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="bg-muted text-muted-foreground">
                    <th className="px-4 py-3 text-left">Producto</th>
                    <th className="px-4 py-3 text-right">Cantidad faltante</th>
                    <th className="px-4 py-3 text-left">Estado</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b">
                    <td className="px-4 py-3 font-medium">Cuadernos Norma</td>
                    <td className="px-4 py-3 text-right">25</td>
                    <td className="px-4 py-3">
                      <Badge variant="secondary">Pendiente</Badge>
                    </td>
                  </tr>
                  <tr className="border-b">
                    <td className="px-4 py-3 font-medium">Chocolates</td>
                    <td className="px-4 py-3 text-right">12</td>
                    <td className="px-4 py-3">
                      <Badge variant="outline">En proceso</Badge>
                    </td>
                  </tr>
                  <tr className="border-b">
                    <td className="px-4 py-3 font-medium">Bolígrafo de lujo</td>
                    <td className="px-4 py-3 text-right">0</td>
                    <td className="px-4 py-3">
                      <Badge>Completado</Badge>
                    </td>
                  </tr>
                  <tr className="border-b">
                    <td className="px-4 py-3 font-medium">Cuaderno de notas</td>
                    <td className="px-4 py-3 text-right">8</td>
                    <td className="px-4 py-3">
                      <Badge variant="secondary">Pendiente</Badge>
                    </td>
                  </tr>
                  <tr className="border-b">
                    <td className="px-4 py-3 font-medium">Caja de bloks para impresora</td>
                    <td className="px-4 py-3 text-right">3</td>
                    <td className="px-4 py-3">
                      <Badge variant="outline">En proceso</Badge>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <footer className="bg-black text-white p-4 md:px-6 lg:px-8 w-full">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div>
            <h3 className="text-lg font-bold mb-2">Contáctanos</h3>
            <ul className="space-y-1">
              <li>Teléfono: 3105751123</li>
              <li>Instagram: https://www.instagram.com/detalles.omega?igsh=MXVvM3lxMTViY2tzMw==</li>
              <li>Dirección: Carrera 100 #139, Bogotá, Colombia</li>
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-2">Conócenos</h3>
            <ul className="space-y-1">
              <li>
                En Omega, combinamos tradición y sostenibilidad para ofrecer productos de la más alta calidad,
                respaldados por un equipo comprometido con la excelencia y la innovación. Nuestra pasión por lo que
                hacemos nos impulsa a superar las expectativas de nuestros clientes cada día.
              </li>
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-2">Medios de Pago</h3>
            <div className="flex items-center space-x-4">
              <img
                src="/placeholder.svg"
                alt="Visa"
                width="50"
                height="30"
                style={{ aspectRatio: "50/30", objectFit: "cover" }}
              />
              <img
                src="/placeholder.svg"
                alt="Mastercard"
                width="50"
                height="30"
                style={{ aspectRatio: "50/30", objectFit: "cover" }}
              />
              <img
                src="/placeholder.svg"
                alt="American Express"
                width="50"
                height="30"
                style={{ aspectRatio: "50/30", objectFit: "cover" }}
              />
            </div>
          </div>
          <div />
        </div>
      </footer>
    </div>
  )
}
